### ISSUE TITLE
Make the medium carjacking anim use the low carjacking anim

### ISSUE THREAD

**Issue by guard3** [gennariarmando/re3#16]

**Comment by MrJago** [comment]
more info

![carjacking](https://user-images.githubusercontent.com/12244359/105568459-3b317180-5cee-11eb-93be-43eb5c587edb.png)

All of the earliest media (not sure if the wireframe counts) shows every car being jacked using the animations enabled with the IS_LOW flag. Unless:

![car_jackedLHS](https://user-images.githubusercontent.com/12244359/105568583-6e283500-5cef-11eb-9b62-25f987a75ed0.gif)

Are car_jackedLHS/RHS used in the game at all? If not, these are probably the animations we're looking for.
