### ISSUE TITLE
Make single door dummy vehicles work? (Bus and Tank only have one entrance)

### ISSUE THREAD

**Issue by guard3** [gennariarmando/re3#20]

**Comment by MrJago** [comment]
![bus exit](https://user-images.githubusercontent.com/12244359/105566620-f0116180-5ce1-11eb-891c-1f01add539e9.png)

Bus works properly now, but it may either need changed animations or the flag IS_BUS to be disabled like in vanilla. Tank will be a tougher challenge altogether, no animation quite makes sense for it:

![tank enter](https://user-images.githubusercontent.com/12244359/105566785-e5a39780-5ce2-11eb-8974-c872519235c0.gif)
