### ISSUE TITLE
Different death situation text

### ISSUE THREAD

**Issue by guard3** [gennariarmando/re3#5]

**Comment by MrJago** [comment]
`{----DEATH MESSAGE ALTERNATIVES---------------------}

[KABOOM]
KABOOOM!

[SPLAT]
SPLAT!

[PANCAK]
PANCAKED!

[SOAKED]
SOAKED!`

Left-overs in american.txt, possible uses suggested by jinx:

- kaboom is for getting exploded in a car
- splat is for death by falling
- pancaked is for getting ran over by a car
- soaked by falling in ocean?
